version: '3'
services:

  postgres:
    image: postgres:alpine
    ports:
      - 5432
    env_file:
      - dbconf-on-premise.env

  s3server:
    image: zenko/cloudserver
    restart: always
    ports:
      - 8000
    stdin_open: true
    tty: true
    volumes:
      - ./config.json:/usr/src/app/config.json

  medical-documentation:
    image: fabix21/medical-records:latest
    volumes:
      - ./medical-records:/usr/src/app
    ports:
      - 8081:8080
    env_file:
      - app-conf.env
      - dbconf-on-premise.env
    depends_on:
      - s3server
      - postgres

